stages:
- build
- deploy
- sonar

services:
  # To obtain a Docker daemon, request a Docker-in-Docker service
  - docker:19.03.1-dind

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: "tcp://docker:2375/"
      
image: 
  name: gitlab-registry.cern.ch/industrial-controls/sw-infra/mvn-dind:3.6.2-19.3.0-jdk11
  entrypoint: [""]   

# Get the settings file from c2mon project
before_script:
  - curl -O -L https://cern.ch/maven/settings-ci.xml

# Fully build and publish master branch
build_and_publish:
  stage: deploy
  tags: 
    - docker-privileged
  script: 
    - docker info
    - mvn -q -U -B -T4 clean deploy --settings settings-ci.xml
  only:
    - master
    
# Just run unit and integration tests on feature branches
build:
  stage: build
  tags: 
    - docker-privileged
  script:
    - docker info
    - mvn -U -B clean test failsafe:integration-test -DskipDockerBuild -DskipDockerTag --settings settings-ci.xml
  except:
    - master

sonar_preview:
  stage: sonar
  script:
    - mvn -q -U -B clean compile sonar:sonar -Dmaven.test.skip=true -Dsonar.host.url=https://cvl-sonarqube.cern.ch -Dsonar.analysis.mode=preview -Dsonar.gitlab.commit_sha=$CI_BUILD_REF -Dsonar.gitlab.ref_name=$CI_BUILD_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID -Dsonar.gitlab.max_major_issues_gate=0 --settings settings-ci.xml --debug -X
  except:
    - master

quality_assurance:
  stage: sonar
  script:
    - mvn package dependency-check:aggregate sonar:sonar -Dmaven.test.skip=true -Dsonar.host.url=https://cvl-sonarqube.cern.ch -Dsonar.dependencyCheck.reportPath=target/dependency-check-report.xml --settings settings-ci.xml
  only:
    - master
