@startuml

title __C2MON-DAQ-OPCUA's Class Diagram__\n

  namespace cern.c2mon.daq.opcua {
    abstract class cern.c2mon.daq.opcua.config.AddressParser {
    }
  }
  

  namespace cern.c2mon.daq.opcua {
    class cern.c2mon.daq.opcua.config.AppConfigProperties {
    }
  }
  

  namespace cern.c2mon.daq.opcua {
    class cern.c2mon.daq.opcua.OPCUAMessageHandler {
    }
  }
  

  namespace cern.c2mon.daq.opcua {
    class cern.c2mon.daq.opcua.RetryDelegate {
    }
  }
  

  namespace cern.c2mon.daq.opcua {
    namespace connection {
      interface cern.c2mon.daq.opcua.connection.Endpoint {
      }
    }
  }
  

  namespace cern.c2mon.daq.opcua {
    namespace connection {
      class cern.c2mon.daq.opcua.connection.MiloEndpoint {
      }
    }
  }
  

  namespace cern.c2mon.daq.opcua {
    namespace connection {
      abstract class cern.c2mon.daq.opcua.connection.MiloMapper {
      }
    }
  }
  

  namespace cern.c2mon.daq.opcua {
    namespace connection {
      class cern.c2mon.daq.opcua.connection.SecurityModule {
      }
    }
  }
  

  namespace cern.c2mon.daq.opcua {
    namespace control {
      class cern.c2mon.daq.opcua.control.ColdFailover {
      }
    }
  }
  

  namespace cern.c2mon.daq.opcua {
    namespace control {
      interface cern.c2mon.daq.opcua.control.Controller {
      }
    }
  }
  

  namespace cern.c2mon.daq.opcua {
    namespace control {
      abstract class cern.c2mon.daq.opcua.control.ControllerBase {
      }
    }
  }
  

  namespace cern.c2mon.daq.opcua {
    namespace control {
      class cern.c2mon.daq.opcua.control.ControllerProxy {
      }
    }
  }
  

  namespace cern.c2mon.daq.opcua {
    namespace control {
      abstract class cern.c2mon.daq.opcua.control.FailoverBase {
      }
    }
  }
  

  namespace cern.c2mon.daq.opcua {
    namespace control {
      interface cern.c2mon.daq.opcua.control.FailoverMode {
      }
    }
  }
  

  namespace cern.c2mon.daq.opcua {
    namespace control {
      interface cern.c2mon.daq.opcua.control.IControllerProxy {
      }
    }
  }
  

  namespace cern.c2mon.daq.opcua {
    namespace control {
      class cern.c2mon.daq.opcua.control.NoFailover {
      }
    }
  }
  

  namespace cern.c2mon.daq.opcua {
    namespace exceptions {
      class cern.c2mon.daq.opcua.exceptions.CommunicationException {
      }
    }
  }
  

  namespace cern.c2mon.daq.opcua {
    namespace exceptions {
      class cern.c2mon.daq.opcua.exceptions.ConfigurationException {
      }
    }
  }
  

  namespace cern.c2mon.daq.opcua {
    namespace exceptions {
      enum ExceptionContext {
      }
    }
  }
  

  namespace cern.c2mon.daq.opcua {
    namespace exceptions {
      class cern.c2mon.daq.opcua.exceptions.LongLostConnectionException {
      }
    }
  }
  

  namespace cern.c2mon.daq.opcua {
    namespace exceptions {
      abstract class cern.c2mon.daq.opcua.exceptions.OPCUAException {
      }
    }
  }
  

  namespace cern.c2mon.daq.opcua {
    namespace mapping {
      class cern.c2mon.daq.opcua.mapping.ItemDefinition {
      }
    }
  }
  

  namespace cern.c2mon.daq.opcua {
    namespace mapping {
      class cern.c2mon.daq.opcua.mapping.SubscriptionGroup {
      }
    }
  }
  

  namespace cern.c2mon.daq.opcua {
    namespace mapping {
      class cern.c2mon.daq.opcua.mapping.TagSubscriptionManager {
      }
    }
  }
  

  namespace cern.c2mon.daq.opcua {
    namespace mapping {
      interface cern.c2mon.daq.opcua.mapping.TagSubscriptionMapReader {
      }
    }
  }
  

  namespace cern.c2mon.daq.opcua {
    namespace mapping {
      interface cern.c2mon.daq.opcua.mapping.TagSubscriptionWriter {
      }
    }
  }
  

  namespace cern.c2mon.daq.opcua {
    namespace security {
      class cern.c2mon.daq.opcua.security.CertificateGenerator {
      }
    }
  }
  

  namespace cern.c2mon.daq.opcua {
    namespace security {
      class cern.c2mon.daq.opcua.security.CertificateLoader {
      }
    }
  }
  

  namespace cern.c2mon.daq.opcua {
    namespace security {
      interface cern.c2mon.daq.opcua.security.Certifier {
      }
    }
  }
  

  namespace cern.c2mon.daq.opcua {
    namespace security {
      abstract class cern.c2mon.daq.opcua.security.CertifierBase {
      }
    }
  }
  

  namespace cern.c2mon.daq.opcua {
    namespace security {
      class cern.c2mon.daq.opcua.security.NoSecurityCertifier {
      }
    }
  }
  

  namespace cern.c2mon.daq.opcua {
    namespace security {
      class cern.c2mon.daq.opcua.security.PkiUtil {
      }
    }
  }
  

  namespace cern.c2mon.daq.opcua {
    namespace tagHandling {
      class cern.c2mon.daq.opcua.tagHandling.AliveWriter {
      }
    }
  }
  

  namespace cern.c2mon.daq.opcua {
    namespace tagHandling {
      class cern.c2mon.daq.opcua.tagHandling.CommandTagHandler {
      }
    }
  }
  

  namespace cern.c2mon.daq.opcua {
    namespace tagHandling {
      class cern.c2mon.daq.opcua.tagHandling.DataTagChanger {
      }
    }
  }
  

  namespace cern.c2mon.daq.opcua {
    namespace tagHandling {
      class cern.c2mon.daq.opcua.tagHandling.DataTagHandler {
      }
    }
  }
  

  namespace cern.c2mon.daq.opcua {
    namespace tagHandling {
      interface cern.c2mon.daq.opcua.tagHandling.IDataTagHandler {
      }
    }
  }
  

  namespace cern.c2mon.daq.opcua {
    namespace tagHandling {
      interface cern.c2mon.daq.opcua.tagHandling.IMessageSender {
      }
    }
  }
  

  namespace cern.c2mon.daq.opcua {
    namespace tagHandling {
      class cern.c2mon.daq.opcua.tagHandling.MessageSender {
      }
    }
  }
  

  cern.c2mon.daq.opcua.config.AppConfigProperties o-- cern.c2mon.daq.opcua.config.AppConfigProperties.KeystoreConfig : keystore
  cern.c2mon.daq.opcua.config.AppConfigProperties o-- cern.c2mon.daq.opcua.config.AppConfigProperties.PKIConfig : pkiConfig
  cern.c2mon.daq.opcua.config.AppConfigProperties o-- cern.c2mon.daq.opcua.config.AppConfigProperties.UsrPwdConfig : usrPwd
  cern.c2mon.daq.opcua.OPCUAMessageHandler .up.|> cern.c2mon.daq.common.ICommandRunner
  cern.c2mon.daq.opcua.OPCUAMessageHandler .up.|> cern.c2mon.daq.common.conf.equipment.IEquipmentConfigurationChanger
  cern.c2mon.daq.opcua.OPCUAMessageHandler -up-|> cern.c2mon.daq.common.EquipmentMessageHandler
  cern.c2mon.daq.opcua.OPCUAMessageHandler o-- cern.c2mon.daq.opcua.tagHandling.AliveWriter : aliveWriter
  cern.c2mon.daq.opcua.OPCUAMessageHandler o-- cern.c2mon.daq.opcua.config.AppConfigProperties : appConfigProperties
  cern.c2mon.daq.opcua.OPCUAMessageHandler o-- cern.c2mon.daq.opcua.tagHandling.CommandTagHandler : commandTagHandler
  cern.c2mon.daq.opcua.OPCUAMessageHandler o-- cern.c2mon.daq.opcua.control.IControllerProxy : controllerProxy
  cern.c2mon.daq.opcua.OPCUAMessageHandler o-- cern.c2mon.daq.opcua.tagHandling.DataTagChanger : dataTagChanger
  cern.c2mon.daq.opcua.OPCUAMessageHandler o-- cern.c2mon.daq.opcua.tagHandling.IDataTagHandler : dataTagHandler
  cern.c2mon.daq.opcua.RetryDelegate o-- cern.c2mon.daq.opcua.config.AppConfigProperties : config
  cern.c2mon.daq.opcua.connection.MiloEndpoint .up.|> cern.c2mon.daq.opcua.connection.Endpoint
  cern.c2mon.daq.opcua.connection.MiloEndpoint .up.|> org.eclipse.milo.opcua.sdk.client.SessionActivityListener
  cern.c2mon.daq.opcua.connection.MiloEndpoint .up.|> org.eclipse.milo.opcua.sdk.client.api.subscriptions.UaSubscriptionManager.SubscriptionListener
  cern.c2mon.daq.opcua.connection.MiloEndpoint o-- cern.c2mon.daq.opcua.mapping.TagSubscriptionMapReader : mapper
  cern.c2mon.daq.opcua.connection.MiloEndpoint o-- cern.c2mon.daq.opcua.tagHandling.IMessageSender : messageSender
  cern.c2mon.daq.opcua.connection.MiloEndpoint o-- cern.c2mon.daq.opcua.RetryDelegate : retryDelegate
  cern.c2mon.daq.opcua.connection.MiloEndpoint o-- cern.c2mon.daq.opcua.connection.SecurityModule : securityModule
  cern.c2mon.daq.opcua.connection.SecurityModule o-- cern.c2mon.daq.opcua.config.AppConfigProperties : config
  cern.c2mon.daq.opcua.control.ColdFailover .up.|> org.eclipse.milo.opcua.sdk.client.SessionActivityListener
  cern.c2mon.daq.opcua.control.ColdFailover -up-|> cern.c2mon.daq.opcua.control.FailoverBase
  cern.c2mon.daq.opcua.control.ColdFailover o-- cern.c2mon.daq.opcua.connection.Endpoint : activeEndpoint
  cern.c2mon.daq.opcua.control.ControllerBase .up.|> cern.c2mon.daq.opcua.control.Controller
  cern.c2mon.daq.opcua.control.ControllerProxy .up.|> cern.c2mon.daq.opcua.control.IControllerProxy
  cern.c2mon.daq.opcua.control.ControllerProxy o-- cern.c2mon.daq.opcua.config.AppConfigProperties : config
  cern.c2mon.daq.opcua.control.ControllerProxy o-- cern.c2mon.daq.opcua.control.Controller : controller
  cern.c2mon.daq.opcua.control.ControllerProxy o-- cern.c2mon.daq.opcua.connection.Endpoint : endpoint
  cern.c2mon.daq.opcua.control.FailoverBase .up.|> cern.c2mon.daq.opcua.control.FailoverMode
  cern.c2mon.daq.opcua.control.FailoverBase -up-|> cern.c2mon.daq.opcua.control.ControllerBase
  cern.c2mon.daq.opcua.control.FailoverBase o-- cern.c2mon.daq.opcua.RetryDelegate : retryDelegate
  cern.c2mon.daq.opcua.control.NoFailover -up-|> cern.c2mon.daq.opcua.control.ControllerBase
  cern.c2mon.daq.opcua.control.NoFailover o-- cern.c2mon.daq.opcua.connection.Endpoint : activeEndpoint
  cern.c2mon.daq.opcua.exceptions.CommunicationException -up-|> cern.c2mon.daq.opcua.exceptions.OPCUAException
  cern.c2mon.daq.opcua.exceptions.ConfigurationException -up-|> cern.c2mon.daq.opcua.exceptions.OPCUAException
  cern.c2mon.daq.opcua.exceptions.LongLostConnectionException -up-|> cern.c2mon.daq.opcua.exceptions.OPCUAException
  cern.c2mon.daq.opcua.exceptions.OPCUAException -up-|> cern.c2mon.daq.tools.equipmentexceptions.EqIOException
  cern.c2mon.daq.opcua.mapping.TagSubscriptionManager .up.|> cern.c2mon.daq.opcua.mapping.TagSubscriptionMapReader
  cern.c2mon.daq.opcua.mapping.TagSubscriptionManager .up.|> cern.c2mon.daq.opcua.mapping.TagSubscriptionWriter
  cern.c2mon.daq.opcua.security.CertificateGenerator -up-|> cern.c2mon.daq.opcua.security.CertifierBase
  cern.c2mon.daq.opcua.security.CertificateGenerator o-- cern.c2mon.daq.opcua.config.AppConfigProperties : config
  cern.c2mon.daq.opcua.security.CertificateLoader -up-|> cern.c2mon.daq.opcua.security.CertifierBase
  cern.c2mon.daq.opcua.security.CertificateLoader o-- cern.c2mon.daq.opcua.config.AppConfigProperties.KeystoreConfig : keystoreConfig
  cern.c2mon.daq.opcua.security.CertificateLoader o-- cern.c2mon.daq.opcua.config.AppConfigProperties.PKIConfig : pkiConfig
  cern.c2mon.daq.opcua.security.CertifierBase .up.|> cern.c2mon.daq.opcua.security.Certifier
  cern.c2mon.daq.opcua.security.NoSecurityCertifier .up.|> cern.c2mon.daq.opcua.security.Certifier
  cern.c2mon.daq.opcua.tagHandling.AliveWriter o-- cern.c2mon.daq.opcua.control.IControllerProxy : controllerProxy
  cern.c2mon.daq.opcua.tagHandling.AliveWriter o-- cern.c2mon.daq.opcua.tagHandling.IMessageSender : messageSender
  cern.c2mon.daq.opcua.tagHandling.CommandTagHandler .up.|> cern.c2mon.daq.common.conf.equipment.ICommandTagChanger
  cern.c2mon.daq.opcua.tagHandling.CommandTagHandler o-- cern.c2mon.daq.opcua.control.IControllerProxy : controllerProxy
  cern.c2mon.daq.opcua.tagHandling.DataTagChanger .up.|> cern.c2mon.daq.common.conf.equipment.IDataTagChanger
  cern.c2mon.daq.opcua.tagHandling.DataTagChanger o-- cern.c2mon.daq.opcua.tagHandling.IDataTagHandler : controller
  cern.c2mon.daq.opcua.tagHandling.DataTagHandler .up.|> cern.c2mon.daq.opcua.tagHandling.IDataTagHandler
  cern.c2mon.daq.opcua.tagHandling.DataTagHandler o-- cern.c2mon.daq.opcua.control.IControllerProxy : controllerProxy
  cern.c2mon.daq.opcua.tagHandling.DataTagHandler o-- cern.c2mon.daq.opcua.mapping.TagSubscriptionManager : mapper
  cern.c2mon.daq.opcua.tagHandling.DataTagHandler o-- cern.c2mon.daq.opcua.tagHandling.IMessageSender : messageSender
  cern.c2mon.daq.opcua.tagHandling.MessageSender .up.|> cern.c2mon.daq.opcua.tagHandling.IMessageSender
  cern.c2mon.daq.opcua.tagHandling.MessageSender .up.|> org.eclipse.milo.opcua.sdk.client.SessionActivityListener


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
