title OPC UA Class Diagram: Connection Component

interface connection.Endpoint {
    {abstract} + callMethod()
    {abstract} + deleteItemFromSubscription()
    {abstract} + disconnect()
    {abstract} + getServerRedundancyNode()
    {abstract} + getUri()
    {abstract} + initialize()
    {abstract} + manageSessionActivityListener()
    {abstract} + read()
    {abstract} + recreateAllSubscriptions()
    {abstract} + recreateSubscription()
    {abstract} + subscribe()
    {abstract} + subscribeWithCallback()
    {abstract} + write()
}

class connection.MiloEndpoint {
    - client : OpcUaClient
    - disconnectedOn : AtomicLong
    {static} - hostRegex : String
    - mode : MonitoringMode
    - sessionActivityListeners : Collection<SessionActivityListener>
    - subscriptionMap : BiMap<Integer, UaSubscription>
    - uri : String
    + MiloEndpoint()
    + callMethod()
    + deleteItemFromSubscription()
    + disconnect()
    + getServerRedundancyNode()
    + getUri()
    + initialize()
    + manageSessionActivityListener()
    + onSessionActive()
    + onSessionInactive()
    + onStatusChanged()
    + onSubscriptionTransferFailed()
    + read()
    + recreateAllSubscriptions()
    + recreateSubscription()
    + setMode()
    + subscribe()
    + subscribeWithCallback()
    + write()
}

abstract class connection.MiloMapper {
    {static} + getDataTagQuality()
    {static} + toObject()
}

class connection.SecurityModule {
    - builder : OpcUaClientConfigBuilder
    - key2Certifier : Map<String, Certifier>
    + SecurityModule()
    + createClientWithListeners()
    + setBuilder()
}
  
connection.MiloEndpoint .up.|> connection.Endpoint
connection.MiloEndpoint .up.|> org.eclipse.milo.opcua.sdk.client.SessionActivityListener
connection.MiloEndpoint .up.|> "org.eclipse.milo.opcua.sdk.client.api.\nsubscriptions.UaSubscriptionManager.SubscriptionListener"
connection.MiloEndpoint o-down- mapping.TagSubscriptionMapReader : mapper
connection.MiloEndpoint o-down- tagHandling.IMessageSender : messageSender
connection.MiloEndpoint o-- connection.SecurityModule : securityModule
connection.SecurityModule o-- AppConfigProperties : config
connection.SecurityModule "[key]" o-- "*" security.Certifier

connection.Endpoint -[hidden]right- org.eclipse.milo.opcua.sdk.client.SessionActivityListener
org.eclipse.milo.opcua.sdk.client.SessionActivityListener -[hidden]down- "org.eclipse.milo.opcua.sdk.client.api.\nsubscriptions.UaSubscriptionManager.SubscriptionListener"
tagHandling.IMessageSender -[hidden]down- mapping.TagSubscriptionMapReader