title OPC UA Class Diagram: Connection Component

interface connection.Endpoint {
    {abstract} + callMethod()
    {abstract} + deleteItemFromSubscription()
    {abstract} + disconnect()
    {abstract} + getServerRedundancyNode()
    {abstract} + getUri()
    {abstract} + initialize()
    {abstract} + manageSessionActivityListener()
    {abstract} + read()
    {abstract} + recreateAllSubscriptions()
    {abstract} + recreateSubscription()
    {abstract} + subscribe()
    {abstract} + subscribeWithCallback()
    {abstract} + write()
}

class connection.MiloEndpoint {
    - client : OpcUaClient
    - disconnectedOn : AtomicLong
    {static} - hostRegex : String
    - mode : MonitoringMode
    - sessionActivityListeners : Collection<SessionActivityListener>
    - subscriptionMap : BiMap<Integer, UaSubscription>
    - uri : String
    + MiloEndpoint()
    + callMethod()
    + deleteItemFromSubscription()
    + disconnect()
    + getServerRedundancyNode()
    + getUri()
    + initialize()
    + manageSessionActivityListener()
    + onSessionActive()
    + onSessionInactive()
    + onStatusChanged()
    + onSubscriptionTransferFailed()
    + read()
    + recreateAllSubscriptions()
    + recreateSubscription()
    + setMode()
    + subscribe()
    + subscribeWithCallback()
    + write()
}

abstract class connection.MiloMapper {
    {static} + getDataTagQuality()
    {static} + toObject()
}

class connection.SecurityModule {
    - builder : OpcUaClientConfigBuilder
    - key2Certifier : Map<String, Certifier>
    + SecurityModule()
    + createClientWithListeners()
    + setBuilder()
}

class security.CertificateGenerator {
  {static} - RSA_SHA256 : String
  {static} - SEVERE_ERROR_CODES : ImmutableSet<Long>
  {static} - SUPPORTED_SIG_ALGS : String[]
  {static} - log : Logger
  + CertificateGenerator()
  + canCertify()
  + getConfig()
  + getSevereErrorCodes()
  + supportsAlgorithm()
  - generateCertificate()
}    

class security.CertificateLoader {
  {static} - SEVERE_ERROR_CODES : ImmutableSet<Long>
  {static} - log : Logger
  + CertificateLoader()
  + canCertify()
  + getKeystoreConfig()
  + getPkiConfig()
  + getSevereErrorCodes()
  + supportsAlgorithm()
  - isKeystoreConfigured()
  - isPkiConfigured()
  - loadCertificateAndKeypair()
}

interface security.Certifier {
  {abstract} + canCertify()
  {abstract} + certify()
  {abstract} + getSevereErrorCodes()
  {abstract} + supportsAlgorithm()
  {abstract} + uncertify()
}

abstract class security.CertifierBase {
  ~ certificate : X509Certificate
  ~ keyPair : KeyPair
  + certify()
  + uncertify()
  # existingCertificateMatchesEndpoint()
  # existingCertificateMatchesSecurityPolicy()
}

class security.NoSecurityCertifier {
  {static} - SEVERE_ERROR_CODES : ImmutableSet<Long>
  {static} - log : Logger
  + NoSecurityCertifier()
  + canCertify()
  + certify()
  + getSevereErrorCodes()
  + supportsAlgorithm()
  + uncertify()
}

class security.PkiUtil {
  {static} + loadCertificate()
  {static} + loadFromPfx()
  {static} + loadPrivateKey()
  {static} - getPemObject()
}

security.CertificateGenerator -up-|> security.CertifierBase
security.CertificateGenerator o-- AppConfigProperties : config
security.CertificateLoader -up-|> security.CertifierBase
security.CertificateLoader o-- AppConfigProperties.KeystoreConfig : keystoreConfig
security.CertificateLoader o-- AppConfigProperties.PKIConfig : pkiConfig
security.CertifierBase .up.|> security.Certifier
security.NoSecurityCertifier .up.|> security.Certifier
  
connection.MiloEndpoint .up.|> connection.Endpoint
connection.MiloEndpoint .up.|> org.eclipse.milo.opcua.sdk.client.SessionActivityListener
connection.MiloEndpoint .up.|> "org.eclipse.milo.opcua.sdk.client.api.\nsubscriptions.UaSubscriptionManager.SubscriptionListener"
connection.MiloEndpoint o-down- mapping.TagSubscriptionMapReader : mapper
connection.MiloEndpoint o-down- tagHandling.IMessageSender : messageSender
connection.MiloEndpoint o-- connection.SecurityModule : securityModule
connection.SecurityModule o-- AppConfigProperties : config
connection.SecurityModule "[key]" o-up- "*" security.Certifier

connection.Endpoint -[hidden]right- org.eclipse.milo.opcua.sdk.client.SessionActivityListener
org.eclipse.milo.opcua.sdk.client.SessionActivityListener -[hidden]right- "org.eclipse.milo.opcua.sdk.client.api.\nsubscriptions.UaSubscriptionManager.SubscriptionListener"

tagHandling.IMessageSender -[hidden]down- mapping.TagSubscriptionMapReader
security.CertificateLoader -[hidden]left-security.CertificateGenerator


AppConfigProperties.KeystoreConfig -up-|> AppConfigProperties
AppConfigProperties.PKIConfig -up-|> AppConfigProperties