title OPC UA DAQ Class Diagram

abstract class config.AddressParser {
  {static} + parse()
}

class OPCUAMessageHandler {
  + connectToDataSource()
  + disconnectFromDataSource()
  + onUpdateEquipmentConfiguration()
  + refreshAllDataTags()
  + refreshDataTag()
  + runCommand()
}

class cern.c2mon.daq.common.EquipmentMessageHandler {
  ~ ApplicationContext context
  + {abstract} connectToDataSource()
  + {abstract} disconnectFromDataSource()
  + {abstract} refreshAllDataTags()
  + {abstract} refreshDataTag()
  + getContext()
  + getEquipmentCommandHandler()
  + getEquipmentConfiguration()
  + getEquipmentConfigurationHandler()
  + getEquipmentMessageSender()
  + setContext()
  + setEquipmentCommandHandler()
  + setEquipmentConfiguration()
  + setEquipmentConfigurationHandler()
  + setEquipmentMessageSender()
  + shutdown()
}

interface IMessageSender {
    {abstract} + initialize()
    {abstract} + onAlive()
    {abstract} + onEquipmentStateUpdate()
    {abstract} + onTagInvalid()
    {abstract} + onValueUpdate()
}

enum IMessageSender.EquipmentState {
  CONNECTION_FAILED
  CONNECTION_LOST
  OK
  message
}

class MessageSender {
    + MessageSender()
    + initialize()
    + onAlive()
    + onEquipmentStateUpdate()
    + onSessionActive()
    + onSessionInactive()
    + onTagInvalid()
    + onValueUpdate()
}

interface cern.c2mon.daq.common.IEquipmentMessageSender {
  {abstract} + sendSupervisionAlive()
  {abstract} + update()
  {abstract} + confirmEquipmentStateIncorrect()
  {abstract} + confirmEquipmentStateOK()
}

interface org.eclipse.milo.opcua.sdk.client.SessionActivityListener {
    {abstract} + onSessionActive()
    {abstract} + onSessionInactive()  
}

interface cern.c2mon.daq.common.ICommandRunner {
  runCommand()
}

interface cern.c2mon.daq.common.conf.equipment.IEquipmentConfigurationChanger {
  onUpdateEquipmentConfiguration()
}

interface control.IControllerProxy {
  {abstract} + connect()
  {abstract} + stop()
  {abstract} + stop()
  {abstract} + callMethod()
  {abstract} + read()
  {abstract} + subscribe()
  {abstract} + unsubscribe()
  {abstract} + write()
}

class taghandling.AliveWriter {
    + initialize()
    + startWriter()
    + stopWriter()
    + updateAndReport()
}

class taghandling.CommandTagHandler {
    + CommandTagHandler()
    + onAddCommandTag()
    + onRemoveCommandTag()
    + onUpdateCommandTag()
    + runCommand()
}
interface cern.c2mon.daq.common.conf.equipment.ICommandTagChanger {
    {abstract} + runCommand()
}

class taghandling.DataTagChanger {
    + onAddDataTag()
    + onRemoveDataTag()
    + onUpdateDataTag()
    + onUpdateEquipmentConfiguration()
}

interface taghandling.IDataTagHandler {
    {abstract} + refreshAllDataTags()
    {abstract} + refreshDataTag()
    {abstract} + removeTag()
    {abstract} + reset()
    {abstract} + subscribeTag()
    {abstract} + subscribeTags()
}

OPCUAMessageHandler .up.|> cern.c2mon.daq.common.ICommandRunner
OPCUAMessageHandler .up.|> cern.c2mon.daq.common.conf.equipment.IEquipmentConfigurationChanger
OPCUAMessageHandler -up-|> cern.c2mon.daq.common.EquipmentMessageHandler
OPCUAMessageHandler o-- taghandling.AliveWriter : aliveWriter
OPCUAMessageHandler o-right- config.AppConfigProperties : appConfigProperties
OPCUAMessageHandler o-- taghandling.CommandTagHandler : commandTagHandler
OPCUAMessageHandler o-- control.IControllerProxy : controllerProxy
OPCUAMessageHandler o-- taghandling.DataTagChanger : dataTagChanger
OPCUAMessageHandler o-- taghandling.IDataTagHandler : dataTagHandler

IMessageSender +-- IMessageSender.EquipmentState
MessageSender o-up- cern.c2mon.daq.common.IEquipmentMessageSender
MessageSender ..|> IMessageSender
MessageSender ..|> org.eclipse.milo.opcua.sdk.client.SessionActivityListener

OPCUAMessageHandler .right.> config.AddressParser
OPCUAMessageHandler .right.> cern.c2mon.daq.common.conf.equipment.ICommandTagChanger
OPCUAMessageHandler ..> IMessageSender

