title OPC UA DAQ Class Diagram: Exception classes   
    
class exceptions.CommunicationException {
  + CommunicationException()
}

class exceptions.ConfigurationException {
  + ConfigurationException()
}

enum ExceptionContext {
  AUTH_ERROR
  BROWSE
  COMMAND_CLASSIC
  COMMAND_TYPE_UNKNOWN
  COMMAND_VALUE_ERROR
  CONNECT
  CREATE_MONITORED_ITEM
  CREATE_SUBSCRIPTION
  DATATAGS_EMPTY
  DELETE_MONITORED_ITEM
  DELETE_SUBSCRIPTION
  DISCONNECT
  EMPTY_SUBSCRIPTION
  ENDPOINT_TYPES_UNKNOWN
  HARDWARE_ADDRESS_UNKNOWN
  METHOD
  METHOD_CODE
  MISSING_URI
  NO_REDUNDANT_SERVER
  OBJINVALID
  PKI_ERROR
  READ
  SECURITY
  SERVER_NODE
  URI_MISSING
  URI_SYNTAX
  WRITE
  message
}

class exceptions.LongLostConnectionException {
  + LongLostConnectionException()
}

abstract class exceptions.OPCUAException {
  {static} + isDataUnavailable()
  {static} + isNodeIdConfigIssue()
  {static} + isSecurityIssue()
  {static} + of()
  # OPCUAException()
}

exceptions.CommunicationException -up-|> exceptions.OPCUAException
exceptions.ConfigurationException -up-|> exceptions.OPCUAException
exceptions.LongLostConnectionException -up-|> exceptions.OPCUAException
exceptions.OPCUAException -up-|> cern.c2mon.daq.tools.equipmentexceptions.EqIOException