title OPC UA DAQ Class Diagram

abstract class config.AddressParser {
  {static} + parse()
}

class OPCUAMessageHandler {
  + connectToDataSource()
  + disconnectFromDataSource()
  + onUpdateEquipmentConfiguration()
  + refreshAllDataTags()
  + refreshDataTag()
  + runCommand()
}

class cern.c2mon.daq.common.EquipmentMessageHandler {
  ~ ApplicationContext context
  + {abstract} connectToDataSource()
  + {abstract} disconnectFromDataSource()
  + {abstract} refreshAllDataTags()
  + {abstract} refreshDataTag()
  + getContext()
  + getEquipmentCommandHandler()
  + getEquipmentConfiguration()
  + getEquipmentConfigurationHandler()
  + getEquipmentMessageSender()
  + setContext()
  + setEquipmentCommandHandler()
  + setEquipmentConfiguration()
  + setEquipmentConfigurationHandler()
  + setEquipmentMessageSender()
  + shutdown()
}

interface cern.c2mon.daq.common.ICommandRunner {
  runCommand()
}

interface cern.c2mon.daq.common.conf.equipment.IEquipmentConfigurationChanger {
  onUpdateEquipmentConfiguration()
}

interface control.IControllerProxy {}

interface tagHandling.AliveWriter {}
interface tagHandling.CommandTagHandler {}
interface tagHandling.IDataTagChanger {}
interface tagHandling.IDataTagHandler {}


OPCUAMessageHandler .up.|> cern.c2mon.daq.common.ICommandRunner
OPCUAMessageHandler .up.|> cern.c2mon.daq.common.conf.equipment.IEquipmentConfigurationChanger
OPCUAMessageHandler -up-|> cern.c2mon.daq.common.EquipmentMessageHandler
OPCUAMessageHandler o-left- tagHandling.AliveWriter : aliveWriter
OPCUAMessageHandler o-left- config.AppConfigProperties : appConfigProperties
OPCUAMessageHandler o-- tagHandling.CommandTagHandler : commandTagHandler
OPCUAMessageHandler o-left- control.IControllerProxy : controllerProxy
OPCUAMessageHandler o-- tagHandling.IDataTagChanger : dataTagChanger
OPCUAMessageHandler o-- tagHandling.IDataTagHandler : dataTagHandler

OPCUAMessageHandler ..> config.AddressParser: parse()
