title OPC UA Class Diagram: Security Component    
class security.CertificateGenerator {
  {static} - RSA_SHA256 : String
  {static} - SEVERE_ERROR_CODES : ImmutableSet<Long>
  {static} - SUPPORTED_SIG_ALGS : String[]
  {static} - log : Logger
  + CertificateGenerator()
  + canCertify()
  + getConfig()
  + getSevereErrorCodes()
  + supportsAlgorithm()
  - generateCertificate()
}    

class security.CertificateLoader {
  {static} - SEVERE_ERROR_CODES : ImmutableSet<Long>
  {static} - log : Logger
  + CertificateLoader()
  + canCertify()
  + getKeystoreConfig()
  + getPkiConfig()
  + getSevereErrorCodes()
  + supportsAlgorithm()
  - isKeystoreConfigured()
  - isPkiConfigured()
  - loadCertificateAndKeypair()
}

interface security.Certifier {
  {abstract} + canCertify()
  {abstract} + certify()
  {abstract} + getSevereErrorCodes()
  {abstract} + supportsAlgorithm()
  {abstract} + uncertify()
}

abstract class security.CertifierBase {
  ~ certificate : X509Certificate
  ~ keyPair : KeyPair
  + certify()
  + uncertify()
  # existingCertificateMatchesEndpoint()
  # existingCertificateMatchesSecurityPolicy()
}

class security.NoSecurityCertifier {
  {static} - SEVERE_ERROR_CODES : ImmutableSet<Long>
  {static} - log : Logger
  + NoSecurityCertifier()
  + canCertify()
  + certify()
  + getSevereErrorCodes()
  + supportsAlgorithm()
  + uncertify()
}

class security.PkiUtil {
  {static} + loadCertificate()
  {static} + loadFromPfx()
  {static} + loadPrivateKey()
  {static} - getPemObject()
}

security.CertificateGenerator -up-|> security.CertifierBase
security.CertificateGenerator o-- AppConfigProperties : config
security.CertificateLoader -up-|> security.CertifierBase
security.CertificateLoader o-- AppConfigProperties.KeystoreConfig : keystoreConfig
security.CertificateLoader o-- AppConfigProperties.PKIConfig : pkiConfig
security.CertifierBase .up.|> security.Certifier
security.NoSecurityCertifier .up.|> security.Certifier