title OPC UA DAQ Class Diagram: TagHandling Component 
class taghandling.AliveWriter {
    + AliveWriter()
    + initialize()
    + startWriter()
    + stopWriter()
    + updateAndReport()
}
class taghandling.CommandTagHandler {
    + CommandTagHandler()
    + onAddCommandTag()
    + onRemoveCommandTag()
    + onUpdateCommandTag()
    + runCommand()
}
class taghandling.DataTagChanger {
    + DataTagChanger()
    + onAddDataTag()
    + onRemoveDataTag()
    + onUpdateDataTag()
    + onUpdateEquipmentConfiguration()
}
class taghandling.DataTagHandler {
    + DataTagHandler()
    + refreshAllDataTags()
    + refreshDataTag()
    + removeTag()
    + reset()
    + subscribeTag()
    + subscribeTags()
}
interface taghandling.IDataTagHandler {
    {abstract} + refreshAllDataTags()
    {abstract} + refreshDataTag()
    {abstract} + removeTag()
    {abstract} + reset()
    {abstract} + subscribeTag()
    {abstract} + subscribeTags()
}

interface IMessageSender {
    {abstract} + initialize()
    {abstract} + onAlive()
    {abstract} + onEquipmentStateUpdate()
    {abstract} + onTagInvalid()
    {abstract} + onValueUpdate()
}

interface control.IControllerProxy {
  {abstract} + connect()
  {abstract} + stop()
  {abstract} + stop()
  {abstract} + callMethod()
  {abstract} + read()
  {abstract} + subscribe()
  {abstract} + unsubscribe()
  {abstract} + write()
}

interface cern.c2mon.daq.common.conf.equipment.ICommandTagChanger {
    {abstract} + onAddCommandTag()
    {abstract} + onRemoveCommandTag()
    {abstract} + onUpdateCommandTag()
}

interface cern.c2mon.daq.common.conf.equipment.IDataTagChanger {
    {abstract} + onAddDataTag()
    {abstract} + onRemoveDataTag()
    {abstract} + onUpdateDataTag()
}

interface mapping.TagSubscriptionManager {
    {abstract} + getTagIdDefinitionMap()
    {abstract} + getGroup()
    {abstract} + getGroups()
    {abstract} + getDefinition()
    {abstract} + getTagId()
    {abstract} + getOrCreateDefinition()
    {abstract} + addTagToGroup()
    {abstract} + removeTag()
    {abstract} + clear()
}

taghandling.AliveWriter o-- control.IControllerProxy : controllerProxy
taghandling.AliveWriter o-- IMessageSender : messageSender
taghandling.CommandTagHandler .up.|> cern.c2mon.daq.common.conf.equipment.ICommandTagChanger
taghandling.CommandTagHandler o-- control.IControllerProxy : controllerProxy
taghandling.DataTagChanger .up.|> cern.c2mon.daq.common.conf.equipment.IDataTagChanger
taghandling.DataTagChanger o-- taghandling.IDataTagHandler : controllerProxy
taghandling.DataTagHandler .up.|> taghandling.IDataTagHandler
taghandling.DataTagHandler o-up- control.IControllerProxy : controllerProxy
taghandling.DataTagHandler o-right- mapping.TagSubscriptionManager : mapper
taghandling.DataTagHandler o-left- IMessageSender : messageSender
taghandling.AliveWriter -[hidden]up- taghandling.CommandTagHandler