@startuml

title __MAPPING's Class Diagram__\n

  namespace cern.c2mon.daq.opcua {
    namespace mapping {
      class cern.c2mon.daq.opcua.mapping.ItemDefinition {
          - clientHandle : UInteger
          {static} - clientHandles : AtomicInteger
          {static} - log : Logger
          - methodNodeId : NodeId
          - nodeId : NodeId
          - timeDeadband : int
          - valueDeadband : float
          - valueDeadbandType : short
          + getClientHandle()
          + getMethodNodeId()
          + getNodeId()
          + getTimeDeadband()
          + getValueDeadband()
          + getValueDeadbandType()
          {static} + of()
          {static} + of()
          {static} + of()
          {static} + toNodeId()
          {static} + toNodeId()
          # ItemDefinition()
          # ItemDefinition()
          {static} # extractOpcAddress()
          - ItemDefinition()
          {static} - toRedundantNodeId()
      }
    }
  }
  

  namespace cern.c2mon.daq.opcua {
    namespace mapping {
      class cern.c2mon.daq.opcua.mapping.SubscriptionGroup {
          - publishInterval : int
          - tagIds : Map<Long, ItemDefinition>
          + SubscriptionGroup()
          + add()
          + contains()
          + getPublishInterval()
          + getTagIds()
          + remove()
          + reset()
          + size()
      }
    }
  }
  

  namespace cern.c2mon.daq.opcua {
    namespace mapping {
      class cern.c2mon.daq.opcua.mapping.TagSubscriptionMapper {
          - subscriptionGroups : Map<Integer, SubscriptionGroup>
          - tagIdDefinitionMap : BiMap<Long, ItemDefinition>
          + TagSubscriptionManager()
          + addTagToGroup()
          + clear()
          + getDefinition()
          + getGroup()
          + getGroups()
          + getOrCreateDefinition()
          + getSubscriptionGroups()
          + getTagId()
          + getTagIdDefinitionMap()
          + removeTag()
          - groupExists()
      }
    }
  }
  

  namespace cern.c2mon.daq.opcua {
    namespace mapping {
      interface cern.c2mon.daq.opcua.mapping.TagSubscriptionReader {
          {abstract} + getDefinition()
          {abstract} + getGroup()
          {abstract} + getGroups()
          {abstract} + getOrCreateDefinition()
          {abstract} + getTagId()
          {abstract} + getTagIdDefinitionMap()
      }
    }
  }
  

  namespace cern.c2mon.daq.opcua {
    namespace mapping {
      interface cern.c2mon.daq.opcua.mapping.TagSubscriptionManager {
          {abstract} + addTagToGroup()
          {abstract} + clear()
          {abstract} + removeTag()
      }
    }
  }
  

  cern.c2mon.daq.opcua.mapping.TagSubscriptionMapper .up.|> cern.c2mon.daq.opcua.mapping.TagSubscriptionReader
  cern.c2mon.daq.opcua.mapping.TagSubscriptionMapper .up.|> cern.c2mon.daq.opcua.mapping.TagSubscriptionManager


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
